[workspace]
resolver = "2"
members = ["sys"]

[package]
name = "rusty_quickjs"
description = "wip"
license = "MIT"
version = "0.0.1"
edition = "2021"

[workspace.dependencies]
rusty_quickjs_sys = { path = "./sys", version = "0.0.1" }

[dependencies]
rusty_quickjs_sys.workspace = true
